### ISSUE TITLE
Automate Tuist upgrade with Renovate

### ISSUE THREAD

**Issue by amarcadet** [asdf-community/asdf-tuist#15]
**Is your feature request related to a problem? Please describe.**

For now Renovate does not support the official `.mise.toml` file format but we can workaround using the "legacy" `.tool-versions` file.

Renovate requires a specific support per tool and thus can't open pull request to upgrade Tuist, see https://docs.renovatebot.com/modules/manager/asdf/#additional-information.

**Describe the solution you'd like**

I think the plugin hosted in this repo could be added to the list of ["upgradable-tooling" here](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/asdf/upgradeable-tooling.ts).

**Describe alternatives you've considered**

Manual updates 🙃 

**Additional context**

Tuist is awesome 🚀

**Comment by pepicrft** [comment]
@amarcadet I created a PR there to add Tuist.

**Comment by pepicrft** [comment]
This has been merged now.
